### ISSUE TITLE
Loose initial roadmap

### ISSUE THREAD

**Issue by cmyr** [cmyr/fea-rs#10]
This project is now at a point where there is a reasonable structure, and most of the work involved in getting to an initial release involves filling in the gaps.

unimplemented parts of the spec:

- [ ] 5.e GSUB contextual substitution
- [ ] 5.f GSUB chaining contextual substitution
- [ ] 5.g GSUB extension substitution
- [ ] 5.h GSUB reverse chaining substitution
- [ ] 6.e GPOS mark-to-lig (needs fonttools impl)
- [ ] 6.f GPOS mark-to-mark (needs fonttools impl)
- [ ] 6.g, 6.h GPOS contextual/chaining contextual
- [ ] 6.i GPOS extension positioning
- [ ] 8.a `aalt`
- [x] 8.b `size`
- [x] 8.c `ss00`
- [x] 8.d `cv00`
- [x] 9.f OS/2 table
- [x] 9.h vmtx table
- [x] 9.i STAT table
- [x] 10. anon blocks
- [x] imports

various bits and bobs
- [ ] compute GDEF from rules when needed

things we need to add in fonttools
- [ ] BASE table
- [ ] vhea table
- [ ] vmtx table
- [ ] GPOS mark-to-lig
- [ ] GPOS mark-to-mark
- [ ] feature parameters
